feat: omnibus release cleanup
feat: support for exact metadata in native image
feat: static-umbrella and prefer-shared linkage modes
feat: stronger hardening flags for both clang and gcc
feat: use oxc parser from truffle typescript
feat: integrate cargo and gradle builds
feat: switch to explicit target triples for cargo
feat: early musl support for rustlibs
feat: build conventions for target info + triples
feat: use native typescript parser by default
feat: ability to enforce custom cargo configs by name
fix: javascript format for esm should follow ts
fix: gc of sections by linker
fix: lto and cflags alignment
fix: cross-lang lto with linker plugins
fix: always produce debug symbols on linux
fix: remove vendored native tls in orogene
fix: remove vendored boringssl
fix: native access to oxc parser
fix: bloat from static rust libs
fix: make orogene and uv conditional
fix: target `x86-64-v3`
fix: better support for clang
fix: aligned cflags for hardening
fix: some issues building against musl
fix: drop sqlite math fns for libm dep
fix: build embedded + benchmarks by default
fix: consolidate `elide.target` and related props
fix: entirely eliminate the "elide natives" root
fix: drop bouncycastle (unused)
fix: drop mosaic and compose (tmp, unused)
fix: respect cflags from all native builds
fix: continued support for cfi/branch protection
fix: drop unused / irrelevant resources
fix: colors break native error printing
fix: copy method visibility for node child process records
fix: drop module preloading
chore: bump version for release
chore: add support for es2024 setting
chore: add run configurations for idea
chore: update llvm/clang → `19.x`
chore: update gradle → `8.13`
chore: update typescript → `5.8.2`
chore: update pnpm → `10.5.2`
chore: update protobuf → `4.28.2`
chore: generate initial new-format reachability metadata
chore: update crates
chore: update pnpm deps
chore: update maven deps
chore: trim unused crates and deps
chore: relocate vm feature classes to `engine`
chore: update api pins
chore: update detekt baselines
chore: update pgo profiles

Signed-off-by: Sam Gammon <sam@elide.dev>

diff --git a/.github/workflows/job.build.yml b/.github/workflows/job.build.yml
--- a/.github/workflows/job.build.yml
+++ b/.github/workflows/job.build.yml
@@ -140,10 +140,6 @@ name: Framework
 
 env:
   BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
-  # SCCACHE_WEBDAV_ENDPOINT: "https://sccache.less.build"
-  # SCCACHE_WEBDAV_USERNAME: "apikey"
-  # SCCACHE_WEBDAV_PASSWORD: ${{ secrets.BUILDLESS_APIKEY }}
-  # SCCACHE_REDIS: "rediss://apikey:${{ secrets.BUILDLESS_APIKEY }}@redis.less.build:6380"
 
 permissions:
   contents: read
@@ -191,8 +187,6 @@ jobs:
       hashes: ${{ steps.hash.outputs.hashes }}
 
     steps:
-      - name: "Setup: Apt Dependencies"
-        run: sudo apt-get install -y libtool-bin build-essential libc6-dev
       - name: "Setup: Harden Runner"
         uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
         with:
@@ -230,6 +224,26 @@ jobs:
             repo.maven.apache.org:443
             scans-in.gradle.com:443
             services.gradle.org:443
+      - name: "Setup: Apt Dependencies"
+        run: |
+          sudo apt-get install -y libtool-bin build-essential libc6-dev libssl-dev
+      - name: "Setup: LLVM 19"
+        run: |
+          wget https://apt.llvm.org/llvm.sh
+          chmod +x llvm.sh
+          sudo apt-get remove clang clangd lld llvm || echo "No LLVM installed; skipping error."
+          sudo ./llvm.sh 19 all
+          export LLVM_PATH=/usr/lib/llvm-19
+          export PATH="$LLVM_PATH/bin:$PATH"
+          export LD_LIBRARY_PATH="$LLVM_PATH/lib:$LD_LIBRARY_PATH"
+          export LLVM_CONFIG="$LLVM_PATH/bin/llvm-config"
+          echo LLVM_PATH=$LLVM_PATH >> $GITHUB_ENV
+          echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH >> $GITHUB_ENV
+          echo LLVM_CONFIG=$LLVM_CONFIG >> $GITHUB_ENV
+          echo PATH=$PATH >> $GITHUB_ENV
+          sudo apt-get remove clang-18 clangd-18 lld-18 llvm-18 || echo "No LLVM 18 installed; skipping error."
+          sudo apt-get autoremove;
+          sudo apt-get clean;
       - name: "Setup: Clear Tooling Cache"
         run: rm -rf /opt/hostedtoolcache
       - name: "Setup: Checkout"
@@ -241,7 +255,7 @@ jobs:
       - name: "Setup: Rust"
         uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
         with:
-          toolchain: nightly
+          toolchain: stable
           components: clippy,rustfmt
           rustflags: ""
       - name: "Setup: SCCache"
@@ -274,23 +288,10 @@ jobs:
       - name: "Setup: PNPM"
         uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
         with:
-          version: "9.2.0"
+          version: "10.5.2"
           run_install: |
             - recursive: true
               args: [--frozen-lockfile, --strict-peer-dependencies]
-      - name: "Setup: LLVM 18"
-        run: |
-          wget https://apt.llvm.org/llvm.sh
-          chmod +x llvm.sh
-          sudo ./llvm.sh 18 all
-          export LLVM_PATH=/usr/lib/llvm-18
-          export PATH="$LLVM_PATH/bin:$PATH"
-          export LD_LIBRARY_PATH="$LLVM_PATH/lib:$LD_LIBRARY_PATH"
-          export LLVM_CONFIG="$LLVM_PATH/bin/llvm-config"
-          echo LLVM_PATH=$LLVM_PATH >> $GITHUB_ENV
-          echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH >> $GITHUB_ENV
-          echo LLVM_CONFIG=$LLVM_CONFIG >> $GITHUB_ENV
-          echo PATH=$PATH >> $GITHUB_ENV
       - name: "Setup: Dependencies"
         run: |
           cargo install cargo-fuzz cargo-insta rustfilt
@@ -349,7 +350,8 @@ jobs:
             --stacktrace \
             -Pelide.ci=true \
             -PbuildSamples=false \
-            -PbuildDocs=false
+            -PbuildDocs=false \
+            -Pelide.buildMode=dev
       - name: "Artifact: Build Outputs"
         uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
         with:
